server:
  port: 8003

spring:
  application:
    name: pcs-auth
  #mysql配置
  datasource:
    url: jdbc:mysql://172.16.0.193:3306/pcs?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: yang1290
    driver-class-name: com.mysql.cj.jdbc.Driver
  #jpa配置
  jpa:
    database: mysql
#    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 172.17.127.72
    database: 10
    port: 6379


#注册中心注册服务
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.0.193:8000/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10

logging.level.org.springframework.security: debug