server:
  port: 8003

spring:
  application:
    name: pcs-auth
  #mysql配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/psc1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
#    url: jdbc:mysql://localhost:3306/psc1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2b8
#    username: root
#    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #jpa配置
  jpa:
    database: mysql
    #    show-sql: true
    hibernate:
      ddl-auto: update
#  redis:
##    host: localhost
#    host: 127.0.0.1
#    database: 12
#    port: 6379


#注册中心注册服务
eureka:
  client:
    serviceUrl:
#      defaultZone: http://10.103.240.237:8000/eureka
      defaultZone: http://112.98.239.146:8000/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10

logging.level.org.springframework.security: debug

